CREATE TABLE EMPLOYEES(
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    CITY VARCHAR(255),
);

INSERT INTO EMPLOYEES(ID,NAME,CITY) VALUES (1,'KIRAN','ELURU'),
INSERT INTO EMPLOYEES(ID,NAME,CITY) VALUES (2,'RAVI','VIJAYAWADA'),
INSERT INTO EMPLOYEES(ID,NAME,CITY) VALUES (3,'KISHORE','HYDERABAD'),
INSERT INTO EMPLOYEES(ID,NAME,CITY) VALUES (4,'KRISHNA','HYDERABAD');
SELECT * FROM EMPLOYEES